version: "3.9"
services: 
    django_server: 
        container_name: django_server
        build: ./ChatWebApp
        volumes: 
            - ./ChatWebApp:/code
        ports: 
          - "8000:8000"
        links:
          - redis
    redis:
        image: redis
        ports:
          - "6379:6379"
    frontend_react:
        container_name: react
        build: ./chatwebapp_frontend
        volumes:
          - ./chatwebapp_frontend:/code
        ports:
          - "3000:3000"