services: 
    django_server: 
        container_name: django_server
        build: ./ChatWebApp
        volumes: 
            - django-data:/code
        ports: 
          - "8000:8000"
        links:
          - redis
    redis:
        container_name: redis
        image: redis
        ports:
          - "6379:6379"
    frontend_react:
        container_name: react
        build: ./chatwebapp_frontend
        ports:
          - "3000:3000"

volumes:
  django-data:
