# Generated by Django 4.0.5 on 2022-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default/default_profile.jpg', upload_to='profile_images/'),
        ),
    ]
