# Generated by Django 4.0.6 on 2022-08-14 13:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='backgroundColor',
            field=colorfield.fields.ColorField(default='#0000aa', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondaryColor',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
    ]
